import type { NextPage } from "next";
import { Fragment } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";

const Scheduler = dynamic(() => import("../components/bryntum/scheduler"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div id="content">
      <Head>
        <title>PO Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="/themes/schedulerpro.stockholm.css?456131"
          id="bryntum-theme"
          rel="stylesheet"
        />
      </Head>
      <Fragment>
        <Scheduler />
      </Fragment>
    </div>
  );
};

export default Home;
